name: Build and Deploy Load Data Docker Image

on:
  push:
    paths:
      - 'docker/load_data'
      - 'code/**'
      - '.github/workflows/load_data.yml'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Authenticate to Google Cloud using your service account key
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # Set up the Cloud SDK (now that authentication is done)
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build Docker Image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/load_data:latest -f docker/load_data .

      - name: Push Docker Image
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/load_data:latest

      - name: Create Vertex AI Notebook Instance
        run: |
          gcloud notebooks instances create my-notebook-instance \
            --location=us-central1-a \
            --vm-image-project=deeplearning-platform-release \
            --vm-image-family=common-cu110-notebooks \
            --container-image-uri=gcr.io/${{ secrets.GCP_PROJECT_ID }}/load_data:latest \
            --container-env=KAGGLE_USERNAME=${{ secrets.KAGGLE_USERNAME }},KAGGLE_KEY=${{ secrets.KAGGLE_KEY }} \
            --machine-type=n1-standard-2 \
            --boot-disk-size=100GB
