name: Build and Deploy Load Data via Vertex AI

on:
  push:
    paths:
      - 'docker/load_data'
      - 'code/**'
      - '.github/workflows/load_data.yml'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2️⃣ Set up Docker Buildx (to use docker-container driver)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3️⃣ Cache Docker Layers
      - name: Cache Docker Layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # 4️⃣ Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # 5️⃣ Set up Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # 6️⃣ Cancel All Previous AI Jobs
      - name: Cancel All Previous Vertex AI Jobs
        run: |
          for REGION in $(gcloud ai locations list --format="value(locationId)")
          do
            echo "Checking jobs in region: $REGION"
            gcloud ai custom-jobs list --region=$REGION --filter="state=JOB_STATE_RUNNING OR state=JOB_STATE_PENDING" --format="value(name)" | \
            xargs -I {} gcloud ai custom-jobs cancel {} --region=$REGION --quiet
          done

      # 7️⃣ Configure Docker for Artifact Registry
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      # 8️⃣ Build Docker Image with Buildx
      - name: Build Docker Image with Buildx
        run: |
          docker buildx build --build-arg KAGGLE_USERNAME=${{ secrets.KAGGLE_USERNAME }} \
                              --build-arg KAGGLE_KEY=${{ secrets.KAGGLE_KEY }} \
                              --cache-from=type=local,src=/tmp/.buildx-cache \
                              --cache-to=type=local,dest=/tmp/.buildx-cache-new \
                              -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/docker-repo/load_data:latest \
                              -f docker/load_data . \
                              --push

      # 9️⃣ Update Docker Cache
      - name: Update Docker Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      # 🔟 Verify Docker Image in Artifact Registry
      - name: Verify Docker Image in Artifact Registry
        run: |
          gcloud artifacts docker images list us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/docker-repo --quiet

      # 1️⃣1️⃣ Create Vertex AI Custom Job YAML Config
      - name: Create Vertex AI Custom Job YAML
        run: |
          cat <<EOF > custom-job.yaml
          display_name: load-data-job
          job_spec:
            worker_pool_specs:
              - machine_spec:
                  machine_type: n1-standard-8
                replica_count: 1
                disk_spec:
                  boot_disk_type: pd-ssd
                  boot_disk_size_gb: 200
                container_spec:
                  image_uri: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/docker-repo/load_data:latest
          EOF

      # 1️⃣2️⃣ Submit Vertex AI Custom Job
      - name: Submit Vertex AI Custom Job
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        run: |
          gcloud ai custom-jobs create --region=us-central1 --config=custom-job.yaml

      # 1️⃣3️⃣ Verify Vertex AI Job Status
      - name: Verify Vertex AI Job Status
        run: |
          gcloud ai custom-jobs list --region=us-central1 --filter="displayName=load-data-job"

      # 1️⃣4️⃣ Cleanup Old Docker Images (Optional)
      - name: Cleanup Old Docker Images
        run: |
          gcloud artifacts docker images delete us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/docker-repo/load_data:latest --quiet || true
