name: Build and Deploy Load Data via Cloud Run Job

on:
  push:
    paths:
      - 'docker/load_data'
      - 'code/**'
      - '.github/workflows/load_data.yml'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1.6.0
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.6.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-docker.pkg.dev --quiet

      - name: Build Docker Image
        run: |
          docker build -t us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/docker-repo/load_data:latest -f docker/load_data .

      - name: Push Docker Image
        run: |
          docker push us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/docker-repo/load_data:latest

      - name: Install Beta Components
        run: gcloud components install beta --quiet

      - name: Create Cloud Run Job
        run: |
          gcloud beta run jobs create load-data-job \
            --image=us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/docker-repo/load_data:latest \
            --region=us \
            --quiet

      - name: Execute Cloud Run Job
        run: |
          gcloud beta run jobs execute load-data-job --region=us --quiet
