name: Train, Track with MLflow, and Upload Sentiment Model

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 1"  # Every Monday at midnight UTC

jobs:
  train-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install Dependencies
      run: pip install -r Model_Pipeline/requirements.txt

    - name: Authenticate with Google Cloud
      env:
        GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      run: |
        echo "$GCP_CREDENTIALS" > gcp-key.json
        export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gcp-key.json
        gcloud auth activate-service-account --key-file=gcp-key.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gcp-key.json" >> $GITHUB_ENV
        gcloud auth list

    - name: Create Directories
      run: |
        mkdir -p Model_Pipeline/Data
        mkdir -p Model_Pipeline/models
        mkdir -p Model_Pipeline/artifacts
        mkdir -p Model_Pipeline/mlruns

    - name: Download Data from GCP
      run: python Model_Pipeline/Data_fetch.py

    - name: Train the Model
      run: python Model_Pipeline/Model_training.py

    - name: Hyperparameter Tuning
      run: python Model_Pipeline/hyperparameter_tuning.py

    - name: Validate the Model
      run: python Model_Pipeline/model_validation.py

    - name: Detect Model Bias
      run: python Model_Pipeline/bias_detection.py

    - name: Run Sensitivity Analysis
      run: python Model_Pipeline/sensitivity_analysis.py

    - name: Version the Model
      run: python Model_Pipeline/model_versioning.py

    - name: Track Experiment with MLflow (GCP Artifact Storage)
      run: python Model_Pipeline/experiment_tracking.py

    - name: Upload Trained Model to GCP
      run: python Model_Pipeline/Model_to_cloud.py

    - name: Upload Trained Model Files
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: Model_Pipeline/models/

    - name: Upload MLflow Logs (Local Run Metadata)
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-logs
        path: Model_Pipeline/mlruns/
